import {buildRegistrationWorkbook} from './registration-export.js?v=20261005-1';
import {auth,db,ADMIN,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,collection,onSnapshot,notify} from './firebase-client.js';
const button=document.getElementById('adminLoginBtn'),area=document.getElementById('adminArea');let stop=[],people=[],roster=[],teams=[],exporting=false;const loaded=new Set(),exportButton=document.getElementById('exportExcelBtn');
function updateExportButton(){exportButton.disabled=exporting||loaded.size!==3||!people.length||auth.currentUser?.email!==ADMIN||!auth.currentUser?.emailVerified;}
exportButton.onclick=async()=>{if(exportButton.disabled)return;exporting=true;updateExportButton();exportButton.textContent='正在匯出…';try{const workbook=buildRegistrationWorkbook(people,roster,teams);const bytes=await workbook.xlsx.writeBuffer();if(auth.currentUser?.email!==ADMIN||!auth.currentUser?.emailVerified)throw Error('請先登入管理者帳號。');const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const link=document.createElement('a');const stamp=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()).replace(/[-: ]/g,'');link.href=url;link.download='工作坊報名名單_'+stamp+'.xlsx';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Excel 報名名單已匯出，共 '+people.length+' 筆。')}catch(error){notify(error.message||'匯出失敗，請重試。')}finally{exporting=false;exportButton.textContent='匯出 Excel';updateExportButton()}};

button.onclick=async()=>{try{if(auth.currentUser?.email===ADMIN)await signOut(auth);else{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider)}}catch(e){const messages={'auth/unauthorized-domain':'目前網站網域尚未獲 Firebase 登入授權，請聯絡管理者設定授權網域。','auth/popup-blocked':'瀏覽器阻擋登入視窗，請允許此網站的彈出式視窗後再試。','auth/popup-closed-by-user':'登入視窗已關閉，尚未完成登入。請再次點選登入。','auth/cancelled-popup-request':'已有登入視窗正在開啟，請完成該視窗的登入。','auth/network-request-failed':'登入連線失敗，請檢查網路後再試。','auth/operation-not-allowed':'Google 登入功能尚未啟用，請聯絡管理者。'};notify(messages[e.code]||'登入失敗（'+(e.code||'unknown')+'），請聯絡管理者。')}};
function render(){updateExportButton();const assigned=roster.filter(p=>p.groupId).length;document.getElementById('stats').replaceChildren();for(const [label,count] of [['報名人數',people.length],['葷食',people.filter(p=>p.meal==='葷食').length],['素食',people.filter(p=>p.meal==='素食').length],['已分組',assigned]]){const card=document.createElement('div');card.className='stat';const text=document.createElement('span');text.textContent=label;const n=document.createElement('b');n.textContent=count;card.append(text,n);document.getElementById('stats').append(card)}const body=document.getElementById('peopleTable');body.replaceChildren();people.forEach(p=>{const row=document.createElement('tr');const group=roster.find(x=>x.id===p.id)?.groupId;const idx=teams.findIndex(g=>g.id===group);[p.name,p.email,p.phone,p.dept,p.meal,idx>=0?'第 '+(idx+1)+' 組':'尚未分組'].forEach(v=>{const td=document.createElement('td');td.textContent=v||'未提供';row.append(td)});body.append(row)});if(!people.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='目前尚無報名資料';row.append(td);body.append(row)}const counts=new Map();people.forEach(p=>counts.set(p.dept,(counts.get(p.dept)||0)+1));document.getElementById('deptStats').textContent=[...counts].map(([d,n])=>d+'：'+n+' 人').join('／')||'目前尚無報名資料';}
onAuthStateChanged(auth,async user=>{stop.forEach(fn=>fn());stop=[];area.classList.add('hidden');people=[];roster=[];teams=[];loaded.clear();updateExportButton();if(!user||user.email!==ADMIN||!user.emailVerified){button.textContent='使用 Google 帳號登入';if(user&&!user.isAnonymous){notify('此帳號沒有管理者權限。');await signOut(auth)}return}button.textContent='登出';area.classList.remove('hidden');notify('已登入管理者帳號。');for(const [name,set] of [['registrations',x=>people=x],['roster',x=>roster=x],['teams',x=>teams=x.sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)||a.id.localeCompare(b.id))]])stop.push(onSnapshot(collection(db,name),s=>{set(s.docs.map(d=>({id:d.id,...d.data()})));loaded.add(name);render()},()=>{loaded.clear();updateExportButton();area.classList.add('hidden');notify('無法讀取統計，請確認管理者權限。')}));});
