import {auth,db,visitor,signOut,onAuthStateChanged,doc,collection,onSnapshot,getDoc,runTransaction,serverTimestamp,notify} from './firebase-client.js?v=20261005-2';
let people=[],groups=[],subscriptions=[],needsNewVisitor=false;const form=document.getElementById('regForm');
const ref=(kind,id)=>doc(db,kind,id);
async function action(fn){try{await fn()}catch(e){notify('操作未完成，請重試。'+(e.message.includes('full')?' 此組已滿。':e.message.includes('assigned')?' 此學員已分組。':''));}}
function render(){
 const available=people.filter(p=>!p.groupId),names=document.getElementById('unassignedNames');names.replaceChildren();if(!available.length)names.textContent=people.length?'所有學員皆已完成分組':'目前尚無報名學員';available.forEach(p=>{const t=document.createElement('span');t.className='name-tag';t.textContent=p.name;names.append(t)});
 const grid=document.getElementById('groupsGrid');grid.replaceChildren();groups.forEach((g,i)=>{const card=document.createElement('div');card.className='group';const header=document.createElement('div');header.className='group-header';const title=document.createElement('h3');title.textContent='第 '+(i+1)+' 組 · '+g.members.length+'/3 人';header.append(title);if(!g.members.length){const x=document.createElement('button');x.type='button';x.className='remove-group';x.textContent='×';x.setAttribute('aria-label','移除第 '+(i+1)+' 組');x.onclick=()=>{if(confirm('確定移除此空組別嗎？'))action(()=>runTransaction(db,async tx=>{const snap=await tx.get(ref('teams',g.id));if(snap.exists()&&!snap.data().members.length)tx.delete(snap.ref)}))};header.append(x)}card.append(header);
 g.members.forEach(id=>{const p=people.find(p=>p.id===id);const row=document.createElement('div');row.className='member';const name=document.createElement('span');name.textContent=p?.name||'載入中';const remove=document.createElement('button');remove.type='button';remove.className='remove-member';remove.textContent='移除';remove.onclick=()=>action(()=>runTransaction(db,async tx=>{const person=await tx.get(ref('roster',id)),team=await tx.get(ref('teams',g.id));if(person.data()?.groupId!==g.id)return;tx.update(person.ref,{groupId:''});tx.update(team.ref,{members:team.data().members.filter(x=>x!==id)})}));row.append(name,remove);card.append(row)});
 const label=document.createElement('label');label.htmlFor='member-'+g.id;label.textContent='新增組員';const select=document.createElement('select');select.id=label.htmlFor;select.add(new Option(g.members.length>=3?'此組已滿':'請選擇姓名',''));available.forEach(p=>select.add(new Option(p.name,p.id)));select.disabled=g.members.length>=3||!available.length;select.onchange=()=>{const id=select.value;if(!id)return;select.disabled=true;action(()=>runTransaction(db,async tx=>{const person=await tx.get(ref('roster',id)),team=await tx.get(ref('teams',g.id));if(!person.exists()||!team.exists())throw Error('missing');if(person.data().groupId)throw Error('assigned');if(team.data().members.length>=3)throw Error('full');tx.update(person.ref,{groupId:g.id});tx.update(team.ref,{members:[...team.data().members,id]})})).finally(render)};if(g.members.length<3)card.append(label,select);const hint=document.createElement('p');hint.className='group-status';hint.textContent=g.members.length<3?'尚需 '+(3-g.members.length)+' 人':'此組人員已滿';card.append(hint);grid.append(card)});
 document.getElementById('groupHint').textContent='已報名 '+people.length+' 人 · 尚未分組 '+available.length+' 人';
}
async function confirmRegistration(){
 const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','registrationConfirmTitle');dialog.style.cssText='border:1px solid #d9e5ec;border-radius:16px;padding:24px;max-width:400px;width:calc(100% - 40px);color:#183247';
 const title=document.createElement('h3');title.id='registrationConfirmTitle';title.textContent='您確定要報名嗎？';dialog.append(title);
 const cancel=document.createElement('button');cancel.type='button';cancel.className='btn secondary';cancel.textContent='取消';
 const confirmButton=document.createElement('button');confirmButton.type='button';confirmButton.className='btn';confirmButton.textContent='確定';confirmButton.style.marginLeft='12px';dialog.append(cancel,confirmButton);document.body.append(dialog);
 return new Promise(resolve=>{let settled=false;const finish=accepted=>{if(settled)return;settled=true;dialog.close();dialog.remove();resolve(accepted)};cancel.onclick=()=>finish(false);confirmButton.onclick=()=>finish(true);dialog.addEventListener('cancel',e=>{e.preventDefault();finish(false)});dialog.showModal();cancel.focus()});
}
form.addEventListener('submit',async e=>{e.preventDefault();if(!(await confirmRegistration()))return;const button=form.querySelector('button[type="submit"]');if(button.disabled)return;button.disabled=true;try{if(needsNewVisitor){await signOut(auth);await visitor();needsNewVisitor=false}let user=await visitor();if((await getDoc(ref('registrations',user.uid))).exists()){await signOut(auth);user=await visitor()}const details={name:form.querySelector('#name').value.trim(),email:form.querySelector('#email').value.trim().toLowerCase(),phone:form.querySelector('#phone').value.trim(),dept:form.querySelector('#dept').value.trim(),meal:form.querySelector('#meal').value,createdAt:serverTimestamp()};if(!details.name||!details.email||!details.phone||!details.dept)throw Error('fields');await runTransaction(db,async tx=>{const existing=await tx.get(ref('registrations',user.uid));if(existing.exists())throw Error('duplicate');tx.set(ref('registrations',user.uid),details);tx.set(ref('roster',user.uid),{name:details.name,groupId:'',createdAt:serverTimestamp()})});if(!people.some(p=>p.id===user.uid))people.push({id:user.uid,name:details.name,groupId:''});render();watchLists(user);const msg=document.getElementById('regMsg');msg.textContent='報名完成！請在右側選擇姓名加入組別。';msg.classList.remove('hidden');form.reset();form.querySelector('#dept').value='國立金門大學都市計畫與景觀學系';needsNewVisitor=true;button.disabled=false;}catch(e){button.disabled=false;notify(e.message.includes('duplicate')?'您已完成報名，請直接進行分組。':'報名未完成，請確認連線後重試。（'+(e.code||e.message||'unknown')+'）')}});
document.getElementById('newGroupBtn').onclick=()=>action(async()=>{const user=await visitor();const team=doc(collection(db,'teams'));await runTransaction(db,async tx=>{tx.set(team,{members:[],createdAt:serverTimestamp(),creator:user.uid})})});
function watchLists(user){subscriptions.forEach(stop=>stop());subscriptions=[];if(!user)return;subscriptions.push(onSnapshot(collection(db,'roster'),s=>{people=s.docs.map(d=>({id:d.id,...d.data()}));render()},()=>notify('無法讀取姓名名單，請稍後再試。')),onSnapshot(collection(db,'teams'),s=>{groups=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)||a.id.localeCompare(b.id));render()},()=>notify('無法讀取分組，請稍後再試。')));}
onAuthStateChanged(auth,watchLists);
try{await visitor();notify('已連線，報名與分組將同步儲存。');}catch(e){notify('連線失敗，請稍後重新整理。');form.querySelector('button[type="submit"]').disabled=true;document.getElementById('newGroupBtn').disabled=true;}
